name: "Trigger edX build"

on: 
  push:
  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: "Trigger the edX build workflow"
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.EDX_BUILD_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'edx',
              repo: 'nedbat-test-trigger-build',
              workflow_id: 'build.yml',
              ref: 'main',
              inputs: {key: "17"}
            })
