name: "Trigger test build"

on: 
  push:
  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: "Trigger the edX build workflow"
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'bilalawan321',
              repo: 'hello-world',
              workflow_id: 'build.yml',
              ref: 'master',
              inputs: {key: "15"}
            })
