name: "Trigger test build"

on: 
  pull_request:
  push:
  workflow_dispatch:

jobs:
  wait-for-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Invoke workflow and handle result
        id: trigger-step
        uses: aurelien-baudet/workflow-dispatch@v2
        with:
          token: ${{ secrets.MY_TOKEN }}
          workflow: 'build.yml'
          repo: 'hello-world'
          inputs: '{ "key": "blah blah", "debug": true }'

  trigger:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: "Trigger the edX build workflow"
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.MY_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'bilalawan321',
              repo: 'hello-world',
              workflow_id: 'build.yml',
              ref: 'master',
              inputs: {key: "00000000"}
            })
